### ISSUE TITLE
Agregar funcion para buscar por rango, nivel, bando.

### ISSUE THREAD

**Issue by jhurtadojerves** [jhurtadojerves/hechizos-hl#1]

**Comment by juliohurtado** [comment]
No entiendo muy bien de que va esta función que mencionas

He preparado todo de tal forma que se pueda hacer con las listas de Neutrales y de la Marca lo mismo que con libros de hechizos.

Fíjate como queda xD

Además ¿Ese cuadro que se abre cuando se da clic en Libros de Hechizos?

Se me ocurre que en la home no esté y que los cuatro menús envien a la lista de todos los hechizos de ese "bando"

Y el submenu aparecería cuando te encuentras dentro de esa página, sin usar js ya

¿Te refieres a eso? @iKenshu

**Comment by juliohurtado** [comment]
2c47089981fe50c4362247c9c27c9aeaee84164b
